In [1]:
import numpy as np
import pandas as pd

In [2]:
csv_data = """Student,Age,Marks,Branch
Amit,18,85,CSE
Priya,19,92,ECE
Rahul,18,76,IT
Sneha,20,88,CSE
Karan,19,67,ME"""

In [3]:
with open ("student.csv","w") as file:
  file.write(csv_data)

In [4]:
df = pd.read_csv("student.csv")
df

  Student  Age  Marks Branch
0    Amit   18     85    CSE
1   Priya   19     92    ECE
2   Rahul   18     76     IT
3   Sneha   20     88    CSE
4   Karan   19     67     ME

In [5]:
df.shape

(5, 4)

In [6]:
df.columns

Index(['Student', 'Age', 'Marks', 'Branch'], dtype='object')

In [7]:
list(df.columns)

['Student', 'Age', 'Marks', 'Branch']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  5 non-null      object
 1   Age      5 non-null      int64
 2   Marks    5 non-null      int64
 3   Branch   5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [9]:
# Find the min,max and avg of marks.
print("Min:", df['Marks'].min())
print("Max:", df['Marks'].max())
print("Avg:", df['Marks'].mean())

Min: 67
Max: 92
Avg: 81.6

In [10]:
# from google.colab import files
# import pandas as pd

# uploaded = files.upload()

In [11]:
import os
print(os.listdir())

['.config', 'student.csv', 'sample_data']

In [12]:
data = """Name,Age,City
Amit,20,Nagpur
Priya,21,Pune
Rahul,19,Mumbai"""

with open("people.csv", "w") as file:
    file.write(data)

df = pd.read_csv("people.csv")

df

    Name  Age    City
0   Amit   20  Nagpur
1  Priya   21    Pune
2  Rahul   19  Mumbai

In [13]:
data = """Name;Age;City
Amit;20;Nagpur
Priya;21;Pune
Rahul;19;Mumbai"""

with open("people.csv", "w") as file:
    file.write(data)

df = pd.read_csv("people.csv",sep = ";")

df

    Name  Age    City
0   Amit   20  Nagpur
1  Priya   21    Pune
2  Rahul   19  Mumbai

In [14]:
data = """Product,Price,Stock
          Laptop,55000,10
          Mouse,700,100
          Keyboard,1500,50"""
with open("data.csv","w") as file:
  file.write(data)
df = pd.read_csv("data.csv")
df

              Product  Price  Stock
0              Laptop  55000     10
1               Mouse    700    100
2            Keyboard   1500     50

In [15]:
data = """Amit,20,Nagpur
Priya,21,Pune
Rahul,19,Mumbai"""

with open("people.csv", "w") as file:
    file.write(data)

df = pd.read_csv("people.csv")

df

    Amit  20  Nagpur
0  Priya  21    Pune
1  Rahul  19  Mumbai

In [16]:
data = """Amit,20,Nagpur
Priya,21,Pune
Rahul,19,Mumbai"""

with open("people.csv", "w") as file:
    file.write(data)

df = pd.read_csv("people.csv",header = None, names = ["Student","Age","City"])

df

  Student  Age    City
0    Amit   20  Nagpur
1   Priya   21    Pune
2   Rahul   19  Mumbai

In [17]:
df.columns = ["Shivam", "Ayush", "City"]
df

  Shivam  Ayush    City
0   Amit     20  Nagpur
1  Priya     21    Pune
2  Rahul     19  Mumbai

In [18]:
df.columns = ["Name","Age","City"]
df

    Name  Age    City
0   Amit   20  Nagpur
1  Priya   21    Pune
2  Rahul   19  Mumbai

In [19]:
data = """Student performance report
Generated by College ABC
Name,Marks,Branch
Amit,85,CSE
Priya,92,ECE
Rahul,76,IT"""

In [20]:
with open("student.csv","w") as file:
  file.write(data)

df = pd.read_csv("student.csv",skiprows=2)
df

    Name  Marks Branch
0   Amit     85    CSE
1  Priya     92    ECE
2  Rahul     76     IT

In [21]:
df["Branch"]

0    CSE
1    ECE
2     IT
Name: Branch, dtype: object

In [22]:
data = """Name,Age,City
Amit,20,Nagpur
Priya,21,Pune
Rahul,19,Mumbai"""

with open("people.csv", "w") as file:
    file.write(data)

df = pd.read_csv("people.csv",usecols=["City"])

df

     City
0  Nagpur
1    Pune
2  Mumbai

In [23]:
data = """Name,Age,City
Amit,20,Nagpur
Priya,21,Pune
Rahul,19,Mumbai"""

with open("data.csv","w") as file:
  file.write(data)

df = pd.read_csv("data.csv",usecols=["Name","City"])
df

    Name    City
0   Amit  Nagpur
1  Priya    Pune
2  Rahul  Mumbai

In [24]:
data = """Name,Age,City
Amit,20,Nagpur
Priya,21,Pune
Rahul,19,Mumbai"""

with open("data.csv","w") as file:
  file.write(data)

df = pd.read_csv("data.csv",nrows=2)
df

    Name  Age    City
0   Amit   20  Nagpur
1  Priya   21    Pune

In [25]:
# Load only the name and age of the first student in df.
data = """Name,Age,City
Amit,20,Nagpur
Priya,21,Pune
Rahul,19,Mumbai"""

with open("data.csv","w") as file:
  file.write(data)

df = pd.read_csv("data.csv",nrows=1,usecols=["Name","Age"])
df

   Name  Age
0  Amit   20

In [26]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Amit", "Priya", "Rahul", "Sneha",
             "Karan", "Neha", "Rohit", "Pooja"],
    "Branch": ["CSE", "ECE", "CSE", "IT",
               "ME", "CSE", "ECE", "IT"],
    "Age": [18, 19, 18, 20, 19, 18, 21, 19],
    "Marks": [78, 92, 65, 88, 45, 95, 56, 72],
    "Attendance": [85, 95, 70, 90, 60, 98, 75, 82]
}

df = pd.DataFrame(data)
df

   Student_ID   Name Branch  Age  Marks  Attendance
0         101   Amit    CSE   18     78          85
1         102  Priya    ECE   19     92          95
2         103  Rahul    CSE   18     65          70
3         104  Sneha     IT   20     88          90
4         105  Karan     ME   19     45          60
5         106   Neha    CSE   18     95          98
6         107  Rohit    ECE   21     56          75
7         108  Pooja     IT   19     72          82

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  8 non-null      int64
 1   Name        8 non-null      object
 2   Branch      8 non-null      object
 3   Age         8 non-null      int64
 4   Marks       8 non-null      int64
 5   Attendance  8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

In [28]:
df.columns

Index(['Student_ID', 'Name', 'Branch', 'Age', 'Marks', 'Attendance'], dtype='object')

In [29]:
list(df.columns)

['Student_ID', 'Name', 'Branch', 'Age', 'Marks', 'Attendance']

In [30]:
df["Name"]

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
5     Neha
6    Rohit
7    Pooja
Name: Name, dtype: object

In [31]:
names = df["Name"]
names

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
5     Neha
6    Rohit
7    Pooja
Name: Name, dtype: object

In [32]:
names.head(1)

0    Amit
Name: Name, dtype: object

In [33]:
names.tail(1)

7    Pooja
Name: Name, dtype: object

In [34]:
names.iloc[0]

'Amit'

In [35]:
names.iloc[-1]

'Pooja'

In [36]:
names[0]

'Amit'

In [37]:
names[7]

'Pooja'

In [38]:
df.Name

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
5     Neha
6    Rohit
7    Pooja
Name: Name, dtype: object

In [39]:
df

   Student_ID   Name Branch  Age  Marks  Attendance
0         101   Amit    CSE   18     78          85
1         102  Priya    ECE   19     92          95
2         103  Rahul    CSE   18     65          70
3         104  Sneha     IT   20     88          90
4         105  Karan     ME   19     45          60
5         106   Neha    CSE   18     95          98
6         107  Rohit    ECE   21     56          75
7         108  Pooja     IT   19     72          82

In [40]:
df[["Name","Age"]]

    Name  Age
0   Amit   18
1  Priya   19
2  Rahul   18
3  Sneha   20
4  Karan   19
5   Neha   18
6  Rohit   21
7  Pooja   19

In [41]:
# Create a new data frame with only the Name,Age and Branch columns in it.
new_df = df[["Name","Age","Branch"]]
new_df

    Name  Age Branch
0   Amit   18    CSE
1  Priya   19    ECE
2  Rahul   18    CSE
3  Sneha   20     IT
4  Karan   19     ME
5   Neha   18    CSE
6  Rohit   21    ECE
7  Pooja   19     IT

In [42]:
df["Name"]

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
5     Neha
6    Rohit
7    Pooja
Name: Name, dtype: object

In [43]:
df[["Name"]]

    Name
0   Amit
1  Priya
2  Rahul
3  Sneha
4  Karan
5   Neha
6  Rohit
7  Pooja

In [44]:
type(df["Name"])

pandas.core.series.Series

In [45]:
type(df[["Name"]])

pandas.core.frame.DataFrame

In [46]:
# Find the index where Left and Right products are equal

# Problem statement: Find an index where the product of all elements
# to its left equals the product of all elements to its right.
# Exclude the element at that index from both products.
# Assume the array contains positive integers greater than zero.
# A = [4,3,5,2,6]
# Ans:2

In [47]:
a = [4,3,5,2,6]

def product(l):
  p = 1
  for e in l:
    p*=e
  return p

for i in range(len(a)):
  if product(a[:i]) == product(a[i+1:]):


   print(i)

2

In [48]:
# # Answer Multiple Range-Sum Queries

# **Problem statement:** Given an array and several queries, each containing a starting index L and an ending index R,
# calculate the sum of elements from index L to index R inclusive

# **Example:**Array: `[3, 5, 2, 8, 4]`

# - Query L = 1, R = 3 → 15
# - Query L = 0, R = 2 → 10

In [49]:
arr = [3, 5, 2, 8, 4]

prefix = [0]
for x in arr:
    prefix.append(prefix[-1] + x)

print(prefix)

def range_sum(L, R):
    return prefix[R + 1] - prefix[L]

print(range_sum(1, 3))
print(range_sum(0, 2))

[0, 3, 8, 10, 18, 22]
15
10

In [50]:
# Calculate the Prefix Sum Array

# **Problem statement:** Given an array, create a new array where each position contains
# the sum of all elements from index 0 to that position.

# **Example:**

# Input: `[2, 4, 1, 5, 3]`

# Output: `[2, 6, 7, 12, 15]`

In [51]:
arr = [2,4,1,5,3]
prefix = arr[:1]

for elem in arr[1:]:
  prefix.append(prefix[-1]+elem)

print(prefix)

[2, 6, 7, 12, 15]

In [52]:
# # Find the Longest Subarray with Equal Numbers of 0s and 1s

# **Problem statement:** Given an array containing only 0 and 1, find the length of the
# longest contiguous subarray containing an equal number of zeros and ones.

# **Example:**

# Input: `[0, 1, 0, 0, 1, 1, 0]`

# Output: `6`

In [53]:
array = [0, 1, 0, 0, 1, 1, 0]

longest = 0

for i in range(len(array)):
    zeros = 0
    ones = 0

    for j in range(i, len(array)):
        if array[j] == 0:
            zeros = zeros + 1
        else:
            ones = ones + 1

        if zeros == ones:
            length = j - i + 1
            if length > longest:
                longest = length

print(longest)

6

In [54]:
# Find the Minimum Length Subarray with Sum at Least S

# Problem statement: Given an array of positive integers and a target S,
# find the minimum length of a contiguous subarray whose sum is at least S.
# Print 0 if no such subarray exists.

# Example: [2, 3, 1, 2, 4, 3], S = 7
# output: [4,3] --> 2

In [55]:
array = [3,2,1,2,4,3]
s = 7

min_len = 7

for i in range(len(array)):
  total = 0
  for j in range(i,len(array)):
    total = total +array[j]

    if total >= s:
      length = j-i+1
      if length < min_len:
        min_len = length
      break

print(min_len)

2