In [1]:
import numpy as np
import pandas as pd

expenses = pd.DataFrame({
    "Category": ["Rent", "Food", "Travel", "Internet", "Shopping"],
    "Amount":[12000, 6000, 1200, 900, 3500],
    "Essential": [True, True, False, True, False]
})

# Expenses greater than 3000
display(expenses[expenses["Amount"] > 3000])

# Essential expenses only
display(expenses[expenses["Essential"] == True])

# Show only the category and amount
display(expenses[["Category", "Amount"]])

# Non-essential expenses costing at least 2000
display(
    expenses[
        (expenses["Essential"] == False) &
        (expenses["Amount"] >= 2000)
    ]
)

   Category  Amount  Essential
0      Rent   12000       True
1      Food    6000       True
4  Shopping    3500      False

   Category  Amount  Essential
0      Rent   12000       True
1      Food    6000       True
3  Internet     900       True

   Category  Amount
0      Rent   12000
1      Food    6000
2    Travel    1200
3  Internet     900
4  Shopping    3500

   Category  Amount  Essential
4  Shopping    3500      False

In [2]:
df = pd.DataFrame({
    "Student": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Python": [85, 92, 60, 78, 45],
    "SQL": [80, 88, 72, 90, 50],
    "Pandas": [82, 95, 65, 86, 40]
})
df

  Student  Python  SQL  Pandas
0    Amit      85   80      82
1   Priya      92   88      95
2   Rahul      60   72      65
3   Sneha      78   90      86
4   Karan      45   50      40

In [3]:
# select python marks
df["Python"]

0    85
1    92
2    60
3    78
4    45
Name: Python, dtype: int64

In [4]:
# Student python marks above 80
df[df["Python"] > 80]

  Student  Python  SQL  Pandas
0    Amit      85   80      82
1   Priya      92   88      95

In [5]:
# students with both Python and SQL marks at least 80
df[
    (df["Python"] >= 80) &
    (df["SQL"] >= 80)
]

  Student  Python  SQL  Pandas
0    Amit      85   80      82
1   Priya      92   88      95

In [6]:
# Display student names and pandas marks
display(df[["Student","Pandas"]])

  Student  Pandas
0    Amit      82
1   Priya      95
2   Rahul      65
3   Sneha      86
4   Karan      40

In [7]:
import pandas as pd

students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Amit", "Priya", "Rahul", "Sneha", "Karan",
        "Neha", "Rohit", "Pooja", "Anjali", "Vikas"
    ],
    "Branch": [
        "CSE", "ECE", "CSE", "IT", "ME",
        "CSE", "ECE", "IT", "EEE", "CSE"
    ],
    "Marks": [82, 91, 68, 88, 76, 95, 79, 72, 85, 74],
    "Attendance": [85, 92, 78, 90, 88, 96, 83, 95, 86, 75],
    "Backlogs": [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    "Placement_Training": [
        "Yes", "Yes", "No", "Yes", "Yes",
        "Yes", "No", "Yes", "Yes", "No"
    ]
})

students

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
2         103   Rahul    CSE     68          78         1                 No
3         104   Sneha     IT     88          90         0                Yes
4         105   Karan     ME     76          88         0                Yes
5         106    Neha    CSE     95          96         0                Yes
6         107   Rohit    ECE     79          83         0                 No
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes
9         110   Vikas    CSE     74          75         0                 No

In [8]:
# Display the first five and last three records.
students.head(5)

   Student_ID   Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101   Amit    CSE     82          85         0                Yes
1         102  Priya    ECE     91          92         0                Yes
2         103  Rahul    CSE     68          78         1                 No
3         104  Sneha     IT     88          90         0                Yes
4         105  Karan     ME     76          88         0                Yes

In [9]:
students.tail(5)

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
5         106    Neha    CSE     95          96         0                Yes
6         107   Rohit    ECE     79          83         0                 No
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes
9         110   Vikas    CSE     74          75         0                 No

In [10]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          10 non-null     int64
 1   Name                10 non-null     object
 2   Branch              10 non-null     object
 3   Marks               10 non-null     int64
 4   Attendance          10 non-null     int64
 5   Backlogs            10 non-null     int64
 6   Placement_Training  10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

In [11]:
# Inspect the dataset's shape,column names,data types,and summary information.
students.shape

(10, 7)

In [12]:
list(students.columns)

['Student_ID',
 'Name',
 'Branch',
 'Marks',
 'Attendance',
 'Backlogs',
 'Placement_Training']

In [13]:
students.dtypes

Student_ID             int64
Name                  object
Branch                object
Marks                  int64
Attendance             int64
Backlogs               int64
Placement_Training    object
dtype: object

In [14]:
students.columns.tolist()

['Student_ID',
 'Name',
 'Branch',
 'Marks',
 'Attendance',
 'Backlogs',
 'Placement_Training']

In [16]:
# Select only the student name,branch,marks,and attendence column.
students[["Name","Branch","Marks","Attendance"]]

     Name Branch  Marks  Attendance
0    Amit    CSE     82          85
1   Priya    ECE     91          92
2   Rahul    CSE     68          78
3   Sneha     IT     88          90
4   Karan     ME     76          88
5    Neha    CSE     95          96
6   Rohit    ECE     79          83
7   Pooja     IT     72          95
8  Anjali    EEE     85          86
9   Vikas    CSE     74          75

In [19]:
# Identify students with marks of the least 75 and attendence of at least 80%.
criteria = (students["Marks"]>= 75) & (students["Attendance"]>= 80)
students[criteria]

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
3         104   Sneha     IT     88          90         0                Yes
4         105   Karan     ME     76          88         0                Yes
5         106    Neha    CSE     95          96         0                Yes
6         107   Rohit    ECE     79          83         0                 No
8         109  Anjali    EEE     85          86         0                Yes

In [20]:
# Restrict the results to students from CSE,IT, or ECE.

In [21]:
students[students["Branch"].isin(["CSE","IT","ECE"])]

   Student_ID   Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101   Amit    CSE     82          85         0                Yes
1         102  Priya    ECE     91          92         0                Yes
2         103  Rahul    CSE     68          78         1                 No
3         104  Sneha     IT     88          90         0                Yes
5         106   Neha    CSE     95          96         0                Yes
6         107  Rohit    ECE     79          83         0                 No
7         108  Pooja     IT     72          95         0                Yes
9         110  Vikas    CSE     74          75         0                 No

In [22]:
# Exclude students with pending backlogs.

In [23]:
students[students["Backlogs"]==0]

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
3         104   Sneha     IT     88          90         0                Yes
4         105   Karan     ME     76          88         0                Yes
5         106    Neha    CSE     95          96         0                Yes
6         107   Rohit    ECE     79          83         0                 No
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes
9         110   Vikas    CSE     74          75         0                 No

In [24]:
# Display the first three eligible students using position-Based indexing.
eligible = students[students["Placement_Training"]=="Yes"]
eligible

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
3         104   Sneha     IT     88          90         0                Yes
4         105   Karan     ME     76          88         0                Yes
5         106    Neha    CSE     95          96         0                Yes
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes

In [25]:
ans = eligible.iloc[:3]
ans

   Student_ID   Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101   Amit    CSE     82          85         0                Yes
1         102  Priya    ECE     91          92         0                Yes
3         104  Sneha     IT     88          90         0                Yes

In [27]:
# Calculate the average marks of eligible students.
# Find the students who are above this avg marks.

In [28]:
# Calculate the average marks of eligible students.
avg = eligible["Marks"].mean()
avg

np.float64(84.14285714285714)

In [29]:
# Find the students who are above this avg marks.
students[students["Marks"] > avg]

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
1         102   Priya    ECE     91          92         0                Yes
3         104   Sneha     IT     88          90         0                Yes
5         106    Neha    CSE     95          96         0                Yes
8         109  Anjali    EEE     85          86         0                Yes

In [30]:
# Save this data into csv file.
eligible.to_csv("data.csv")