In [20]:
import pandas as pd

students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan", "Neha"],
    "Python": [80, 95, 45, 70, 30, 88],
    "SQL": [75, 90, 50, 65, 40, 92],
    "Statistics": [85, 92, 40, 80, 35, 90],
    "Attendance": [90, 95, 65, 80, 55, 98],
    "Branch": ["CSE", "IT", "CSE", "ECE", "ME", "IT"]
})

print(students)

   Student_ID   Name  Python  SQL  Statistics  Attendance Branch
0         101   Amit      80   75          85          90    CSE
1         102  Priya      95   90          92          95     IT
2         103  Rahul      45   50          40          65    CSE
3         104  Sneha      70   65          80          80    ECE
4         105  Karan      30   40          35          55     ME
5         106   Neha      88   92          90          98     IT

In [3]:
# Create a column Academic_year and assign avalue 2026 to each student.
students["Academic_year"] = 2026
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year
0,101,Amit,80,75,85,90,CSE,2026
1,102,Priya,95,90,92,95,IT,2026
2,103,Rahul,45,50,40,65,CSE,2026
3,104,Sneha,70,65,80,80,ECE,2026
4,105,Karan,30,40,35,55,ME,2026
5,106,Neha,88,92,90,98,IT,2026

In [4]:
# Assign a mentor to each student.
students["Mentor"] = [
    "Shivam","Riya","Khushi","Kunal","Aman","Shivam"
]
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,Mentor
0,101,Amit,80,75,85,90,CSE,2026,Shivam
1,102,Priya,95,90,92,95,IT,2026,Riya
2,103,Rahul,45,50,40,65,CSE,2026,Khushi
3,104,Sneha,70,65,80,80,ECE,2026,Kunal
4,105,Karan,30,40,35,55,ME,2026,Aman
5,106,Neha,88,92,90,98,IT,2026,Shivam

In [6]:
# Total_marks = python + SQL + STATISTICS
students["Total_marks"] = (students["Python"]
                           +students["SQL"]
                           +students["Statistics"]
                           )

In [7]:
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,Mentor,Total_marks
0,101,Amit,80,75,85,90,CSE,2026,Shivam,240
1,102,Priya,95,90,92,95,IT,2026,Riya,277
2,103,Rahul,45,50,40,65,CSE,2026,Khushi,135
3,104,Sneha,70,65,80,80,ECE,2026,Kunal,215
4,105,Karan,30,40,35,55,ME,2026,Aman,105
5,106,Neha,88,92,90,98,IT,2026,Shivam,270

In [10]:
# new_column - % marks
students["Percentage"] =round((
     students["Total_marks"]*100/300),2)

In [11]:
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,Mentor,Total_marks,Percentage
0,101,Amit,80,75,85,90,CSE,2026,Shivam,240,80.00
1,102,Priya,95,90,92,95,IT,2026,Riya,277,92.33
2,103,Rahul,45,50,40,65,CSE,2026,Khushi,135,45.00
3,104,Sneha,70,65,80,80,ECE,2026,Kunal,215,71.67
4,105,Karan,30,40,35,55,ME,2026,Aman,105,35.00
5,106,Neha,88,92,90,98,IT,2026,Shivam,270,90.00

In [15]:
# Average of each subject across all students --> class avg for each subject --> column-wise avg
# Average of the three subjects for each student --> row_wise avg --> avg for each student

# axis = 0 --> column_wise
# axis = 1 --> row_wise

print(students[["Python","SQL","Statistics"]].mean())

Python        68.000000
SQL           68.666667
Statistics    70.333333
dtype: float64

In [16]:
print(students[["Python","SQL","Statistics"]].mean(axis=1))

0    80.000000
1    92.333333
2    45.000000
3    71.666667
4    35.000000
5    90.000000
dtype: float64

In [18]:
# Which students scored better in python than in SQL, and by how much?
students["Python_SQL_Difference"] = (
    students["Python"] -students["SQL"]
)
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,Mentor,Total_marks,Percentage,Python_SQL_Difference
0,101,Amit,80,75,85,90,CSE,2026,Shivam,240,80.00,5
1,102,Priya,95,90,92,95,IT,2026,Riya,277,92.33,5
2,103,Rahul,45,50,40,65,CSE,2026,Khushi,135,45.00,-5
3,104,Sneha,70,65,80,80,ECE,2026,Kunal,215,71.67,5
4,105,Karan,30,40,35,55,ME,2026,Aman,105,35.00,-10
5,106,Neha,88,92,90,98,IT,2026,Shivam,270,90.00,-4

In [19]:
# Assign 5 grace marks to each students for Python.
students["Python"]+=5
students
# issue with this code --> exceeds 100 marks

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,Mentor,Total_marks,Percentage,Python_SQL_Difference
0,101,Amit,85,75,85,90,CSE,2026,Shivam,240,80.00,5
1,102,Priya,100,90,92,95,IT,2026,Riya,277,92.33,5
2,103,Rahul,50,50,40,65,CSE,2026,Khushi,135,45.00,-5
3,104,Sneha,75,65,80,80,ECE,2026,Kunal,215,71.67,5
4,105,Karan,35,40,35,55,ME,2026,Aman,105,35.00,-10
5,106,Neha,93,92,90,98,IT,2026,Shivam,270,90.00,-4

In [21]:
students["Python"]

0    80
1    95
2    45
3    70
4    30
5    88
Name: Python, dtype: int64

In [22]:
students["python_2"] = (students["Python"]+10).clip(upper = 100)
students["python_2"]

0     90
1    100
2     55
3     80
4     40
5     98
Name: python_2, dtype: int64

In [23]:
students["Python"]

0    80
1    95
2    45
3    70
4    30
5    88
Name: Python, dtype: int64

In [24]:
import numpy as np
students["Python3"] = np.minimum(students["Python"]+15,100)
students["Python3"]

0     95
1    100
2     60
3     85
4     45
5    100
Name: Python3, dtype: int64

In [26]:
students["Python"]

0    80
1    95
2    45
3    70
4    30
5    88
Name: Python, dtype: int64