In [1]:
import pandas as pd

In [2]:
data = {
    "Student": ["Amit", "Priya", "Rahul", "Sneha", "Karan",
                "Neha", "Rohit", "Pooja", "Arjun", "Meera"],
    "Age": [18, 19, 18, 20, 19, 18, 21, 19, 20, 18],
    "Marks": [78, 92, 65, 88, 45, 95, 56, 72, 81, 69],
    "Attendance": [85, 95, 70, 90, 60, 98, 75, 82, 88, 68],
    "Branch": ["CSE", "ECE", "CSE", "IT", "ME",
               "CSE", "ECE", "IT", "ME", "CSE"]
}

df = pd.DataFrame(data)

df

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE
3   Sneha   20     88          90     IT
4   Karan   19     45          60     ME
5    Neha   18     95          98    CSE
6   Rohit   21     56          75    ECE
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [3]:
df.head()

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE
3   Sneha   20     88          90     IT
4   Karan   19     45          60     ME

In [4]:
df.head(3)

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE

In [5]:
df.tail()

  Student  Age  Marks  Attendance Branch
5    Neha   18     95          98    CSE
6   Rohit   21     56          75    ECE
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [6]:
df.tail(3)

  Student  Age  Marks  Attendance Branch
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [7]:
df.sample()

  Student  Age  Marks  Attendance Branch
7   Pooja   19     72          82     IT

In [8]:
df.sample()

  Student  Age  Marks  Attendance Branch
9   Meera   18     69          68    CSE

In [9]:
df.sample()

  Student  Age  Marks  Attendance Branch
2   Rahul   18     65          70    CSE

In [10]:
df.sample(5)

  Student  Age  Marks  Attendance Branch
4   Karan   19     45          60     ME
1   Priya   19     92          95    ECE
8   Arjun   20     81          88     ME
2   Rahul   18     65          70    CSE
3   Sneha   20     88          90     IT

In [11]:
df.sample(3)

  Student  Age  Marks  Attendance Branch
6   Rohit   21     56          75    ECE
9   Meera   18     69          68    CSE
7   Pooja   19     72          82     IT

In [12]:
df.sample(3)

  Student  Age  Marks  Attendance Branch
6   Rohit   21     56          75    ECE
3   Sneha   20     88          90     IT
5    Neha   18     95          98    CSE

In [13]:
df.sample(3,random_state=42)

  Student  Age  Marks  Attendance Branch
8   Arjun   20     81          88     ME
1   Priya   19     92          95    ECE
5    Neha   18     95          98    CSE

In [14]:
df.sample(3,random_state=42)

  Student  Age  Marks  Attendance Branch
8   Arjun   20     81          88     ME
1   Priya   19     92          95    ECE
5    Neha   18     95          98    CSE

In [15]:
df.sample(3,random_state=1)

  Student  Age  Marks  Attendance Branch
2   Rahul   18     65          70    CSE
9   Meera   18     69          68    CSE
6   Rohit   21     56          75    ECE

In [16]:
df.sample(3,random_state=1)

  Student  Age  Marks  Attendance Branch
2   Rahul   18     65          70    CSE
9   Meera   18     69          68    CSE
6   Rohit   21     56          75    ECE

In [17]:
df.sample(3,random_state=30)

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE

In [18]:
large_df = pd.DataFrame({
    "Employee_ID": range(1001, 1021),
    "Salary": [
        25000, 30000, 28000, 45000, 50000,
        32000, 38000, 41000, 29000, 60000,
        35000, 48000, 52000, 27000, 39000,
        43000, 31000, 55000, 36000, 47000
    ]
})

large_df

    Employee_ID  Salary
0          1001   25000
1          1002   30000
2          1003   28000
3          1004   45000
4          1005   50000
5          1006   32000
6          1007   38000
7          1008   41000
8          1009   29000
9          1010   60000
10         1011   35000
11         1012   48000
12         1013   52000
13         1014   27000
14         1015   39000
15         1016   43000
16         1017   31000
17         1018   55000
18         1019   36000
19         1020   47000

In [19]:
large_df.sample(5)

    Employee_ID  Salary
15         1016   43000
5          1006   32000
0          1001   25000
19         1020   47000
7          1008   41000

In [20]:
large_df.sample(5,random_state=23)

    Employee_ID  Salary
0          1001   25000
10         1011   35000
2          1003   28000
1          1002   30000
4          1005   50000

In [21]:
large_df.sample(5,random_state=23)

    Employee_ID  Salary
0          1001   25000
10         1011   35000
2          1003   28000
1          1002   30000
4          1005   50000

In [22]:
large_df.shape

(20, 2)

In [23]:
large_df.size

40

In [24]:
row,column = df.shape
row

10

In [25]:
column

5

In [26]:
row,column = large_df.shape
row

20

In [27]:
column

2

In [28]:
r = df.shape[0]
c = df.shape[1]
r,c

(10, 5)

In [29]:
r,c = df.shape
size = r*c
size

50

In [30]:
# check whether a dataset has a records.
if df.shape[0] > 0:
  print("The dataset contain records.")
else:
  print("The dataset is empty")

The dataset contain records.

In [31]:
# create an empty dataframe.

data = pd.DataFrame()
data

Empty DataFrame
Columns: []
Index: []

In [32]:
data.shape

(0, 0)

In [33]:
data.size

0

In [34]:
data = {
    "Student": ["Amit", "Priya", "Rahul", "Sneha", "Karan",
                "Neha", "Rohit", "Pooja", "Arjun", "Meera"],
    "Age": [18, 19, 18, 20, 19, 18, 21, 19, 20, 18],
    "Marks": [78, 92, 65, 88, 45, 95, 56, 72, 81, 69],
    "Attendance": [85, 95, 70, 90, 60, 98, 75, 82, 88, 68],
    "Branch": ["CSE", "ECE", "CSE", "IT", "ME",
               "CSE", "ECE", "IT", "ME", "CSE"]
}

df = pd.DataFrame(data)

df

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE
3   Sneha   20     88          90     IT
4   Karan   19     45          60     ME
5    Neha   18     95          98    CSE
6   Rohit   21     56          75    ECE
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [35]:
# Write a code to get all the column names.
print(df.columns)

Index(['Student', 'Age', 'Marks', 'Attendance', 'Branch'], dtype='object')

In [36]:
list(df.columns)

['Student', 'Age', 'Marks', 'Attendance', 'Branch']

In [37]:
# check if a specific column exists in the dataframe.
if "Age" in df.columns:
  print("Column exist.")
else:
  print("Column not exist,Check the spelling.")

Column exist.

In [38]:
# check if a specific column exists in the dataframe.
if "Agee" in df.columns:
  print("Column exist.")
else:
  print("Column not exist,Check the spelling.")

Column not exist,Check the spelling.

In [39]:
df = pd.DataFrame({
    "Employee_ID": range(1001, 1006),
    "Salary": [
        25000, 30000, 28000, 45000, 50000,
    ]
})

df

   Employee_ID  Salary
0         1001   25000
1         1002   30000
2         1003   28000
3         1004   45000
4         1005   50000

In [40]:
# change the names of the column
df.columns = ["ID","salary"]
df

     ID  salary
0  1001   25000
1  1002   30000
2  1003   28000
3  1004   45000
4  1005   50000

In [41]:
# Find the product of all elements except the current element

# Probrlem statement:create a result array in which each position contains
# the product of all the other array elements,without dividing by the current element.

# Example: [1,2,3,4]
# Output:  [24,12,8,6]

# Logic:
# pick an element:
# inner loop: find prd of all, and skip that elem using index.

In [42]:
arr = [1,2,3,4]

product = []

for i in range(len(arr)):
  p = 1
  for j in range(len(arr)):
    if i != j:
      p*=arr[j]

  product.append(p)

print(product)

[24, 12, 8, 6]

In [43]:
# # Left rotate an array by one position

# Problem statement:
# Given an array,all elements one position to the left.
# The first element should move to the last position.

# Example: [10,20,30,40,50]
# OUTPUT:[20,30,40,50,10]

In [45]:
a = [10,20,30,40,50]
a[1:]+a[:1]

[20, 30, 40, 50, 10]

In [46]:
# # Right Rotate an Array by k positions

# Problem statement: Rotate an array to the right by k position.

# Example: [1,2,3,4,5],k=2
# output: [4,5,1,2,3]

In [49]:
a = [1,2,3,4,5]
a[3:]+a[:3]

[4, 5, 1, 2, 3]

In [ ]:
#  Find the union of Two arrays

#  problem statement: Point every distinct element that appears in either of two arrays.
#  Do not print duplicate.

# a = [1,2,3,4]
# b = [3,4,5,6]
# ans = [1,2,3,4,5,6]

In [51]:
a = [1,2,3,4]
b = [3,4,5,6]

ans = []

for e in a:
  if e not in ans:
    ans.append(e)


for e1 in b:
  if e1 not in ans:
    ans.append(e1)

print(ans)

[1, 2, 3, 4, 5, 6]

In [52]:
# Find the Intersection without Duplicates

# Problem statement: Print distinct elements common to both arrays,
# even if an element appears multiple times in either innput.

# Example:[2,2,4,6,6,8] and [2,6,,6,10]
# ans = [2,6]

In [53]:
a = [2,2,4,6,6,8]
b = [2,6,6,10]

ans = []

for e in a:
  if e in b and e not in ans:
    ans.append(e)

ans

[2, 6]