In [ ]:
# How to deal with missing data?
# 1- drop the missing value -->dropna()
# 2- filling the missing values -->fillna()

In [1]:
import pandas as pd
import numpy as np

students = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Marks": [85, 92, None, 78, None],
    "Attendance": [90, 95, 75, None, 80],
    "Branch": ["CSE", "IT", "CSE", None, "ME"]
})

students

    Name  Marks  Attendance Branch
0   Amit   85.0        90.0    CSE
1  Priya   92.0        95.0     IT
2  Rahul    NaN        75.0    CSE
3  Sneha   78.0         NaN   None
4  Karan    NaN        80.0     ME

In [2]:
data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [55000, 700, np.nan, 12000],
    "Stock": [10, np.nan, 35, 8]
}

df = pd.DataFrame(data)
df

    Product    Price  Stock
0    Laptop  55000.0   10.0
1     Mouse    700.0    NaN
2  Keyboard      NaN   35.0
3   Monitor  12000.0    8.0

In [3]:
df.dtypes

Product     object
Price      float64
Stock      float64
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  4 non-null      object
 1   Price    3 non-null      float64
 2   Stock    3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.0+ bytes

In [5]:
df = pd.DataFrame({
    "Employee": ["Amit", None, "Sneha"],
    "Salary": [45000, np.nan, 60000],
    "Experience": [2, 4, None]
})

df

  Employee   Salary  Experience
0     Amit  45000.0         2.0
1     None      NaN         4.0
2    Sneha  60000.0         NaN

In [6]:
df.isna()

   Employee  Salary  Experience
0     False   False       False
1      True    True       False
2     False   False        True

In [7]:
df.isna().sum()

Employee      1
Salary        1
Experience    1
dtype: int64

In [8]:
df.isnull().sum()

Employee      1
Salary        1
Experience    1
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(3)

In [10]:
df.isna().sum().sum()

np.int64(3)

In [11]:
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Marks": [85, np.nan, 76, 90, np.nan],
    "Attendance": [90, 95, np.nan, 80, np.nan]
})

df

    Name  Marks  Attendance
0   Amit   85.0        90.0
1  Priya    NaN        95.0
2  Rahul   76.0         NaN
3  Sneha   90.0        80.0
4  Karan    NaN         NaN

In [12]:
df.isnull()

    Name  Marks  Attendance
0  False  False       False
1  False   True       False
2  False  False        True
3  False  False       False
4  False   True        True

In [13]:
df.isnull().sum()

Name          0
Marks         2
Attendance    2
dtype: int64

In [14]:
df.isnull().sum().sum()

np.int64(4)

In [15]:
df.notna()

   Name  Marks  Attendance
0  True   True        True
1  True  False        True
2  True   True       False
3  True   True        True
4  True  False       False

In [17]:
df.notna().all(axis = 1)

0     True
1    False
2    False
3     True
4    False
dtype: bool

In [18]:
df.notna().any(axis = 1)

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [19]:
df.notna().any()

Name          True
Marks         True
Attendance    True
dtype: bool

In [20]:
df.isna().any()

Name          False
Marks          True
Attendance     True
dtype: bool

In [21]:
df.isna().all()

Name          False
Marks         False
Attendance    False
dtype: bool

In [23]:
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
    "Marks": [85, np.nan, 76, 90, np.nan],
    "Attendance": [np.nan, np.nan, np.nan, np.nan, np.nan]
})

df

    Name  Marks  Attendance
0   Amit   85.0         NaN
1  Priya    NaN         NaN
2  Rahul   76.0         NaN
3  Sneha   90.0         NaN
4  Karan    NaN         NaN

In [24]:
df.isna().all()

Name          False
Marks         False
Attendance     True
dtype: bool