In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Amit", "Priya", "Rahul", "Sneha",
             "Karan", "Neha", "Rohit", "Pooja"],
    "Age": [18, 19, 18, 20, 19, 18, 21, 19],
    "Branch": ["CSE", "ECE", "CSE", "IT",
               "ME", "CSE", "ECE", "IT"],
    "Marks": [78, 92, 65, 88, 45, 95, 56, 72],
    "Attendance": [85, 95, 70, 90, 60, 98, 75, 82]
})

df

   Student_ID   Name  Age Branch  Marks  Attendance
0         101   Amit   18    CSE     78          85
1         102  Priya   19    ECE     92          95
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60
5         106   Neha   18    CSE     95          98
6         107  Rohit   21    ECE     56          75
7         108  Pooja   19     IT     72          82

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  8 non-null      int64
 1   Name        8 non-null      object
 2   Age         8 non-null      int64
 3   Branch      8 non-null      object
 4   Marks       8 non-null      int64
 5   Attendance  8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

In [3]:
df[["Age"]]

   Age
0   18
1   19
2   18
3   20
4   19
5   18
6   21
7   19

In [4]:
df["Age"]

0    18
1    19
2    18
3    20
4    19
5    18
6    21
7    19
Name: Age, dtype: int64

In [5]:
df

   Student_ID   Name  Age Branch  Marks  Attendance
0         101   Amit   18    CSE     78          85
1         102  Priya   19    ECE     92          95
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60
5         106   Neha   18    CSE     95          98
6         107  Rohit   21    ECE     56          75
7         108  Pooja   19     IT     72          82

In [ ]:
# loc ==> accesses using the row labels and the columns label.

In [7]:
df.loc[1]

Student_ID      102
Name          Priya
Age              19
Branch          ECE
Marks            92
Attendance       95
Name: 1, dtype: object

In [9]:
df.loc[7]

Student_ID      108
Name          Pooja
Age              19
Branch           IT
Marks            72
Attendance       82
Name: 7, dtype: object

In [11]:
# 1st ,3rd,4th student info
df.loc[[0,2,3]]

   Student_ID   Name  Age Branch  Marks  Attendance
0         101   Amit   18    CSE     78          85
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90

In [12]:
df.loc[[1]]

   Student_ID   Name  Age Branch  Marks  Attendance
1         102  Priya   19    ECE     92          95

In [14]:
# row: 2nd to 5th
df.loc[1:5]

   Student_ID   Name  Age Branch  Marks  Attendance
1         102  Priya   19    ECE     92          95
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60
5         106   Neha   18    CSE     95          98

In [15]:
# loc --> both start and end indices are included

In [16]:
df[["Age"]]

   Age
0   18
1   19
2   18
3   20
4   19
5   18
6   21
7   19

In [17]:
df.loc[:,"Age"]

0    18
1    19
2    18
3    20
4    19
5    18
6    21
7    19
Name: Age, dtype: int64

In [19]:
# cols:Age,Marks,Branch
df.loc[:,["Age","Marks","Branch"]]

   Age  Marks Branch
0   18     78    CSE
1   19     92    ECE
2   18     65    CSE
3   20     88     IT
4   19     45     ME
5   18     95    CSE
6   21     56    ECE
7   19     72     IT

In [21]:
# students 2nd to 6th --> Age,Marks
df.loc[1:5,["Age","Marks"]]

   Age  Marks
1   19     92
2   18     65
3   20     88
4   19     45
5   18     95

In [22]:
# students 3rd and 5th --> Age,Branch
df.loc[2:4,["Age","Branch"]]

   Age Branch
2   18    CSE
3   20     IT
4   19     ME

In [ ]:
# # iloc --> accesses using indexing
# loc --> label(L)
# iloc --> index(I)

In [23]:
# 2nd row --->
df.iloc[1]

Student_ID      102
Name          Priya
Age              19
Branch          ECE
Marks            92
Attendance       95
Name: 1, dtype: object

In [26]:
# last student info using both loc and iloc
df.iloc[-1]

Student_ID      108
Name          Pooja
Age              19
Branch           IT
Marks            72
Attendance       82
Name: 7, dtype: object

In [27]:
df.loc[7]

Student_ID      108
Name          Pooja
Age              19
Branch           IT
Marks            72
Attendance       82
Name: 7, dtype: object

In [29]:
# 2nd,4th,and 5th row using iloc
df.iloc[[1,3,4]]

   Student_ID   Name  Age Branch  Marks  Attendance
1         102  Priya   19    ECE     92          95
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60

In [31]:
# show the details of students: 2nd to 6th
df.iloc[1:5] # end index is excluded

   Student_ID   Name  Age Branch  Marks  Attendance
1         102  Priya   19    ECE     92          95
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60

In [32]:
df.iloc[1:6]

   Student_ID   Name  Age Branch  Marks  Attendance
1         102  Priya   19    ECE     92          95
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60
5         106   Neha   18    CSE     95          98

In [34]:
# Age and marks column using iloc.
df.iloc[:,[2,4]]

   Age  Marks
0   18     78
1   19     92
2   18     65
3   20     88
4   19     45
5   18     95
6   21     56
7   19     72

In [ ]:
# Find the Smallest Difference Between Two Sorted Arrays

# Problem statement: Given two arrays sorted in ascending order,
#  find the smallest absolute difference between an element of the first array and an element of the second array.

# Example:
# A = [1, 4, 8, 10]
# B = [2, 5, 9, 12]

# Output:1

In [35]:

A = [1, 4, 8, 10]
B = [2, 5, 9, 12]

def find_smallest_diff(arr1, arr2):
    smallest_diff = float('inf')

    for i in range(len(arr1)):
        for j in range(len(arr2)):
            diff = abs(arr1[i] - arr2[j])

            if diff < smallest_diff:
                smallest_diff = diff

    return smallest_diff

print(find_smallest_diff(A, B))

1

In [36]:
a = [1, 4, 8, 10]
b = [2, 5, 9, 12]

n = len(a)
m = len(b)

i = 0
j = 0
minimum = abs(a[0] - b[0])

while i < n and j < m:
    diff = abs(a[i] - b[j])

    if diff < minimum:
        minimum = diff

    if a[i] < b[j]:
        i += 1
    else:
        j += 1

print(f"Minimum difference = {minimum}")

Minimum difference = 1