Pandas

In [1]:
# Student name
# student ID
# Branch
# Attendence percentage
# examination marks
# study hours
# placement status

In [2]:
# # Pandas can be used to perform the following:
# Organizing data into rows and columns.
# Reading data from CSV and Excel files.
# Selecting specific rows and columns.
# Filtering records based on conditions.
# Handling missing values.
# Cleaning inconsistent data.
# Calculating statistics.
# Grouping and summarizing information.
# Combining datasets.
# Preparing data for visualization and machine learning.

In [3]:
student_names = ["Amit","Priya","Rahul","Sneha"]
marks = [85,92,67,78]

print(student_names)
print(marks)

['Amit', 'Priya', 'Rahul', 'Sneha']
[85, 92, 67, 78]

In [4]:
avg_marks = sum(marks)/len(marks)
avg_marks

80.5

In [5]:
import pandas as pd

In [6]:
pd.__version__

'2.2.3'

In [7]:
# dictonary:

# coll: names --> [n1,n2..]
# coll: marks --> [m1.m2..]

# pd.DataFrame(dict)

In [8]:
students = pd.DataFrame(
    {
        "Name":["Amit","Priya","Rahul","Sneha"],
        "Marks":[85,92,67,78]
    })
print(students)

    Name  Marks
0   Amit     85
1  Priya     92
2  Rahul     67
3  Sneha     78

In [9]:
students

    Name  Marks
0   Amit     85
1  Priya     92
2  Rahul     67
3  Sneha     78

In [10]:
# Series
import pandas as pd

marks = pd.Series([85,92,67,78,90])

print(marks)

0    85
1    92
2    67
3    78
4    90
dtype: int64

In [11]:
temperature = pd.Series([30,32,31,29,35,34,33])
temperature.mean()

np.float64(32.0)

In [12]:
temperature.min()

29

In [13]:
temperature.max()

35

In [14]:
temperature.size

7

In [15]:
len(temperature)

7

In [16]:
person = pd.Series(["Shivam",34,5.7,False])
print(person)

0    Shivam
1        34
2       5.7
3     False
dtype: object

In [17]:
# month name --> index
# sales --> series values

In [18]:
data = pd.Series(
    [100,200,500,450]
    )
data

0    100
1    200
2    500
3    450
dtype: int64

In [19]:
data[1]

np.int64(200)

In [20]:
data = pd.Series(
    [100,200,500,450],
    index = ["jan","feb","march","April"]
    )
data

jan      100
feb      200
march    500
April    450
dtype: int64

In [21]:
data[1]

/tmp/ipykernel_2048/3862107824.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[1]

np.int64(200)

In [22]:
data["feb"]

np.int64(200)

In [23]:
# what % of sales comes from jan?
data["jan"]*100/data.sum()

np.float64(8.0)

In [24]:
# series:
# subjects ==> marks

In [25]:
data = pd.Series([100,80,90,45,70],
                 index = ["python","SQL","ML","AI","Maths"])
data

python    100
SQL        80
ML         90
AI         45
Maths      70
dtype: int64

In [26]:
s = {
    "Python":100,
    "SQL":80,
    "ML":90,
    "Marhs":70
}

s

{'Python': 100, 'SQL': 80, 'ML': 90, 'Marhs': 70}

In [27]:
import pandas as pd
data = pd.Series(s)
data

Python    100
SQL        80
ML         90
Marhs      70
dtype: int64

In [28]:
# create a pandas series from a numpy array.
import numpy as np
data = np.array([1000,39,49.69,76])
import pandas as pd
data = pd.Series(data)
data

0    1000.00
1      39.00
2      49.69
3      76.00
dtype: float64

In [29]:
# Write a code to craete a numpy array of marks(out of 100) and then assign 10 bonus marks to each.
marks = np.array([56,78,98,77,98])
n_marks = marks+10
n_marks

array([ 66,  88, 108,  87, 108])

In [30]:
n_marks = np.minimum(marks+10,100)
n_marks

array([ 66,  88, 100,  87, 100])

In [31]:
marks.min()

np.int64(56)

In [32]:
marks = pd.Series([60,70,80,90])
marks+5

0    65
1    75
2    85
3    95
dtype: int64